### ISSUE TITLE
Failed to download league/uri-hostname-parser from dist...

### ISSUE THREAD

**Issue by SDKiller** [thephpleague/uri-hostname-parser#1]
## Issue summary

```
  - Removing jeremykendall/php-domain-parser (3.0.0)
  - Installing league/uri-hostname-parser (1.0.0): Downloading (100%)

 Failed to download league/uri-hostname-parser from dist: The archive may contain identical file names with different capitalization (which fails on
 case insensitive filesystems): ZipArchive::extractTo(.../vendor/composer/554ec116/thephpleague-uri-hostname-pa
rser-e8d579d\data/leaguepsl::ICANN-SECTION-5a3cc7f81795bb2e48e848af42d287b4.cache): failed to open stream: Invalid argument
    Now trying to download from source

...

- Installing league/uri-hostname-parser (1.0.0): Cloning e8d579d034 from cache


  [RuntimeException]
  Failed to clone https://github.com/thephpleague/uri-hostname-parser.git via https, ssh protocols, aborting.
  - https://github.com/thephpleague/uri-hostname-parser.git
    fatal: destination path '...\vendor\league\uri-hostname-parser' already exists and is not an empty directory.
  - git@github.com:thephpleague/uri-hostname-parser.git
    fatal: destination path '...\vendor\league\uri-hostname-parser' already exists and is not an empty directory.
```

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| League\Uri\PublicSuffix version |  |
| PHP version | 7.0 |
| OS Platform | Windows 7 |

## Standalone code, or other way to reproduce the problem

```
 composer update --prefer-dist --ignore-platform-reqs --no-dev --no-progress --no-interaction --no-suggest --optimize-autoloader
```

**Comment by nyamsprod** [comment]
@SDKiller I need more information what was it you were trying to do ? Update League\Uri or just install this package on its own to replace PDP ?

**Comment by SDKiller** [comment]
I was updating dependencies, `"league/uri": "*"` is in my `composer.json`

**Comment by nyamsprod** [comment]
strange I did not run into this issue ... maybe you did not have to correct dependencies ... you tried with the master ?

**Comment by SDKiller** [comment]
I ran into it doing `composer update`.
But attempt to clone repository also fails on windows

```
15:07	Clone failed
			unable to create file data/leaguepsl::ICANN-SECTION-5a3cc7f81795bb2e48e848af42d287b4.cache (Invalid argument)
			unable to checkout working tree

```

**Comment by SDKiller** [comment]
https://msdn.microsoft.com/ru-ru/library/windows/desktop/aa365247(v=vs.85).aspx#naming_conventions

```
The following reserved characters:
< (less than)
> (greater than)
: (colon)
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
* (asterisk)
```

**Comment by nyamsprod** [comment]
Could you try the master to see if all is good now ?

**Comment by SDKiller** [comment]
Yes, it's ok.

Could you make a new release?
Now it is nesessary to explicitly set `"league/uri-hostname-parser": "dev-master"` in `composer.json` for the project with `"minimum-stability": "stable"`.

**Comment by nyamsprod** [comment]
yep I'll make a new release later today I've added another fix in the meantime thanks for reporting the bug

**Comment by nyamsprod** [comment]
version 1.0.1 is released
