### ISSUE TITLE
How can I change the manager used by League\Uri\resolve_domain function?

### ISSUE THREAD

**Issue by pamil** [thephpleague/uri-hostname-parser#2]
## Issue summary

I've `league/uri-hostname-parser` downloaded as a dependency and my `vendor` directory is not writable, so the cache used by the default manager created in `League\Uri\resolve_domain` function throws an exception. How can I change the manager which is being used there?

### System informations

| Information | Description |
|--------------|---------|
| League\Uri\PublicSuffix version | could not find any package named PublicSuffix  |
| PHP version | 7.1.+ |
| OS Platform | Mac OS, Linux |

League\Uri packages installed:

```
league/uri                                       5.2.0   URI manipulation library
league/uri-components                            1.6.0   URI components manipulation library
league/uri-hostname-parser                       1.0.4   ICANN base hostname parsing implemented in PHP.
league/uri-interfaces                            1.0.0   Common interface for URI representation
league/uri-manipulations                         1.3.0   URI manipulation library
league/uri-parser                                1.3.0   userland URI parser RFC 3986 compliant
league/uri-schemes                               1.1.1   URI manipulation library
```

## Standalone code, or other way to reproduce the problem

1. Install as a dependency in a project
2. Make vendor directory not writable (`chmod 555 -R vendor` should do)
3. Call `League\Uri\resolve_domain` function

### Expected result

The function returns `Domain` object.

### Actual result

The function throws an exception, stacktraces included in the following issues:

- https://github.com/Sylius/Sylius/issues/9105
- https://github.com/Payum/Payum/issues/734

**Comment by pamil** [comment]
There's also another issue connected with this one - 
 how to make existing `resolve_domain` calls (like https://github.com/thephpleague/uri-components/blob/master/src/Components/Host.php#L253) use custom manager / cache?

**Comment by nyamsprod** [comment]
@pamil changing the cache is possible if you are using the package independently you can use any PSR-16 implementation and you will be good to go. 

On the other hand if you are using the package with league URI not using the cache will be difficult (ie: resolve_domain is design to work with the filecache as the package was created to be a drop in replacement of php-domain-parser version 3.0. 

the php-domain-parser usage in league uri was already done using a file cache inside the vendor directory. So even with v5.0 you would had have the same issue.

A way to fix this is to not thrown if the cache is not updated but to return false instead. But this would mean that your cache won't get updated at all. But since you are effectively restraining writing permission it means that you know what you are doing.

**Comment by nyamsprod** [comment]
so the "fix" is to make the package not throw on error but return false. I hate returning false but that's the only alternative I can think of If you have a better Idea a PR is welcomed 👍

**Comment by nyamsprod** [comment]
@pamil I found a better solution but it will include:
- updating this package (adding a missing method)
- updating the uri component package as well (adding 1 method and refactoring the class a little bit)
I'll keep you posted

**Comment by pamil** [comment]
Great, keeping my fingers crossed! I'm sorry I haven't come up with any idea myself, but I'm kinda new to Uri package and I have only a partial knowledge about what does it do in fact :)

**Comment by nyamsprod** [comment]
@pamil the first step is done .. a  new version for this package has been released version 1.1 with the missing method which was `__set_state` 🎉 next i'll update the Uri component today or tomorrow 
and when it's done I'll release a new Uri meta package maybe 5.2.1 or 5.3.0 I'll see which feats better SemVer

**Comment by pamil** [comment]
Wow, thanks a lot! 🎉

**Comment by nyamsprod** [comment]
but I'm still puzzle as to why you are chmoding the vendor directory 🤔 Any reason for that ? Since any composer install/ and or update will likely require the vendor directory to be writable ?

**Comment by pamil** [comment]
Chmod is only to make it reproducible on other environments. 

There are two steps for Platform.sh:

1. Building the image - warming up the cache, downloading dependencies, installing assets
2. Deploying the image - migrating the database, etc. 

When deploying, the whole filesystem is frozen, so you can't change any files there.

**Comment by nyamsprod** [comment]
So this blocks any cache relying on filesystem access then 😢 . 

Anyway the patch is ready :tada: 

https://github.com/thephpleague/uri-components/tree/feature/add-host-resolver-injection

When released you'll be able to cache using any PSR-16 implementation like describe in the documentation and you'll be able to directly instantiate the host with the domain resolver directly 👍 

The current behavior will stay as a fallback if no resolver is given on instantiation to avoid BC break.

**Comment by nyamsprod** [comment]
@pamil you can make a composer update of league/uri you'll get the last version of uri components with all the fix ... see https://github.com/thephpleague/uri-components/pull/11 for more info. I'll close this issue as it is resolved

**Comment by pamil** [comment]
Thanks a lot @nyamsprod! To be honest, I haven't expected such a fast reply (and an even faster fix), so I don't have enough time this week to look at it thoroughly (releasing Sylius 1.1.0 now), but I'll let you know the next week ASAP :)
