### ISSUE TITLE
Fatal error: Default value for parameters with a class type hint can only be NULL in /var/www/html/application/vendor/league/uri-hostname-parser/src/functions.php on line 34

### ISSUE THREAD

**Issue by iamdeadman** [thephpleague/uri-hostname-parser#4]
## Issue summary

Hi, I am trying to install a php yii template (https://youdate.hauntd.me/documentation/installation.html) and after installing the dependencies when I try to move the files to my development web root it shows an error in the browser. 

So, when I try to see the apache logs I see - 

`Fatal error: Default value for parameters with a class type hint can only be NULL in /var/www/html/application/vendor/league/uri-hostname-parser/src/functions.php on line 34
`

I think it might have to do something with my development hostname and

### System informations

| Information | Description |
|--------------|---------|
| League\Uri\PublicSuffix 1.1.0 |  |
| PHP 7.1  |
| OS Ubuntu 16.04 |  |

## Standalone code, or other way to reproduce the problem

https://youdate.hauntd.me/documentation/installation.html

### Expected result

Web application preview in development environment

### Actual result

Warning: Unsupported declare 'strict_types' in /var/www/html/application/vendor/league/uri-hostname-parser/src/functions.php on line 15

Fatal error: Default value for parameters with a class type hint can only be NULL in /var/www/html/application/vendor/league/uri-hostname-parser/src/functions.php on line 34

**Comment by nyamsprod** [comment]
> Warning: Unsupported declare 'strict_types' in /var/www/html/application/vendor/league/uri-hostname-parser/src/functions.php on line 15

To me this means that you are not using PHP7.0. Please review your application settings. This has nothing to do with the library

**Comment by kalpitpandit** [comment]
I am also facing same. I am using 7.0

> PHP 7.0.33-6+ubuntu14.04.1+deb.sury.org+3 (cli) (built: Apr 10 2019 12:06:04) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.33-6+ubuntu14.04.1+deb.sury.org+3, Copyright (c) 1999-2017, by Zend Technologies
