### ISSUE TITLE
Fatal error: Default value for parameters with a class type hint can only be NULL in /var/www/html/application/vendor/league/uri-hostname-parser/src/functions.php on line 34

### ISSUE THREAD

**Issue by iamdeadman** [thephpleague/uri-hostname-parser#5]
## Issue summary

Hi, I am trying to install a php yii template (https://youdate.hauntd.me/documentation/installation.html) and after installing the dependencies when I try to move the files to my development web root it shows an error in the browser. 

So, when I try to see the apache logs I see - 

`Fatal error: Default value for parameters with a class type hint can only be NULL in /var/www/html/application/vendor/league/uri-hostname-parser/src/functions.php on line 34
`

I think it might have to do something with my development hostname and so I tried to update the /etc/hosts file but it didn't help. 
It would be great if you have anything that could help in fixing / further debugging of this issue
Also, please let me know if I can provide any other information that could help fixing this

### System informations

| Information | Description |
|--------------|---------|
| League\Uri\PublicSuffix 1.1.0 |  |
| PHP 7.1  |
| OS Ubuntu 16.04 |  |

## Standalone code, or other way to reproduce the problem

https://youdate.hauntd.me/documentation/installation.html

### Expected result

Web application preview in development environment

### Actual result

Warning: Unsupported declare 'strict_types' in /var/www/html/application/vendor/league/uri-hostname-parser/src/functions.php on line 15

Fatal error: Default value for parameters with a class type hint can only be NULL in /var/www/html/application/vendor/league/uri-hostname-parser/src/functions.php on line 34

**Comment by nyamsprod** [comment]
duplicate issue see #4
